// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Fueling",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Fueling",
            targets: ["AppModule"],
            bundleIdentifier: "com.example.fueling",
            teamIdentifier: "",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .car),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(path: "..")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "FuelingModel", package: "FuelingApp"),
                .product(name: "FuelingUI", package: "FuelingApp")
            ],
            path: "."
        )
    ]
)
