#!/usr/bin/env python3
"""gen_server.py -- bake the injected server URL into the DS build.

Reads FUELING_SERVER_URL (the same environment variable the playground app
and the Android port use), defaulting to the local test server through the
emulator NAT (http://10.0.2.2:8080), and emits <build>/ServerConfig.swift
with the host, port, and Host-header constants Network.swift compiles
against. The host may be a hostname (resolved on-device via DNS) or a
dotted-quad IP.

No URL is ever committed: the default points at the local test server, and
anything else exists only in the generated file under build/ (gitignored).

The Nintendo DS has no TLS stack, so https URLs are rejected outright --
point FUELING_SERVER_URL at a plain-http endpoint or a local proxy.

Usage: gen_server.py <build-dir>
"""

import os
import sys


def main() -> None:
    build_dir = sys.argv[1] if len(sys.argv) > 1 else "build"
    url = os.environ.get("FUELING_SERVER_URL", "").strip() or "http://10.0.2.2:8080"

    if url.startswith("https://"):
        sys.exit(
            "FUELING_SERVER_URL: https is not supported on the Nintendo DS "
            "(no TLS stack); use a plain-http endpoint or a local proxy"
        )
    if url.startswith("http://"):
        url = url[len("http://") :]
    url = url.rstrip("/")

    if "/" in url:
        sys.exit("FUELING_SERVER_URL: paths are not supported, use scheme://host[:port]")

    host, _, port_text = url.partition(":")
    if not host:
        sys.exit("FUELING_SERVER_URL: missing host")
    port = int(port_text) if port_text else 80
    if not 0 < port < 65536:
        sys.exit("FUELING_SERVER_URL: invalid port")

    host_header = host if port == 80 else f"{host}:{port}"
    contents = f"""//
//  ServerConfig.swift -- generated by tools/gen_server.py, do not edit.
//
//  Injected from FUELING_SERVER_URL at build time (default: the local test
//  server through the emulator NAT).
//

let serverHost: StaticString = "{host}"
let serverPort: UInt16 = {port}
let serverHostHeader: StaticString = "{host_header}"
"""

    path = os.path.join(build_dir, "ServerConfig.swift")
    os.makedirs(build_dir, exist_ok=True)
    # Only rewrite on change so make doesn't rebuild unnecessarily.
    try:
        with open(path) as existing:
            if existing.read() == contents:
                return
    except FileNotFoundError:
        pass
    with open(path, "w") as out:
        out.write(contents)
    print(f"server: http://{host_header}")


if __name__ == "__main__":
    main()
